### ISSUE TITLE
Waybar buttons

### ISSUE THREAD

**Issue by j-dominguez9** [mbrignall/sway-dotfiles#1]
Hey, thank you so much for putting this together and releasing it. I am relatively new to Sway, so please forgive me if I am doing something wrong, but when I copied the waybar config files, the only buttons that were clickable (i.e., that is, they were responsive to being clicked) were the window selections on the far left. The remaining (calendar/time, wifi, battery, sound, and power) are not clickable. Am I missing something? Thanks again.

**Comment by mbrignall** [comment]
#Hey,

Thanks for the question.

I have been using Fedora and that had features installed by default from Gnome. So a lot of the clickable Waybar buttons point to those for example:

`"on-click": "gnome-control-center wifi",`
`"on-click": "gnome-control-center sound",`
`"on-click": "gnome-calendar"`
`"on-click": "gnome-power-statistics"`

(In `waybar/config` file.)

Bluetooth is a module available on dnf called Blueberry:

`"on-click": "blueberry",`

So if you're using Fedora you could install that.

I don't have a power button on my Waybar. 

For Ubuntu I've used stuff like:

pavucontrol for sound
Blueman GUI for Bluetooth.

Let me know what distro you're on and a bit more information on your set up and I'll get the buttons going. 

:smile_cat:

**Comment by mbrignall** [comment]
On a side note regarding power:

I've tide sway/mode to the keybindings in Sway:

shift+super+e

Brings up the power menu.

Hope that helps.
